language: java
jdk:
   - oraclejdk8

env:
   global:
      - secure: "tkBAQwa0pXkGvNDv9VxsV3Eq0u9ZJCnH62JzD9Y0VRGSsC1uszHZ2ChihAWiiFgivKln3KKb2BlMn7O2HIYjzkY54N7jEdLJzWKJIPAoFJFquK0Cyi/3BRvlhR+e+Oh7GvhWjiOZFwjBfvFkxHFbsQsq5VCP04i3jPGh3wnr0Ns="
      - secure: "fyrge5fWmxi7rVkvtcLyiBfSjc27J0K5JQdFcVyoRwXH5BcTf9Vz02jUmh04ulojdINRppdh7yAFa2S9b0DOQXe65DyT/Ackinpl4YPzL0W2ABoWSw6Hwp0IrMCXGPOC6fqC+4gtJoxEedGV3DK3EVr344jNl4UFQwkj3E4PjOc="
      - secure: "OFHM1q76Zox2FzWb6AcPzQ9M1pV00EZxqVveFY7kYdJYMKe0+k+520o/YI7RJXc1DCKHtJnKcKtd8q0lZtDDtzjq5gq/0AYtT1ZRpPv/W9a8fzL39GaUrFfXLEvrsGKQjQq3spDY4j0q5FV/vOrz38KXIrcZGf6RJAFcMY33Zzs="
      - secure: "TIAALjzvbyrzuuOZeAWlGvlmYFyxHlKiiNh/B7YhqgnRClfHC5oa4I3TIoPom2TNsmkNxlOhM5909KCKWfcanavfg0AS+/V0/8zdm0M6b5f9a9gYWNNXSsNmDp2XHI6N+t86YpBWh/x/EltZKxzgGT0Eo4Y19sFfXtevviCs9Ws="
      - secure: "PchnjgO0v8XHiuIi3KEhFi4fKCSacBLLhfFVKy0uKFZ4vCtwuHUUBxjZafdZA6bndatwSpUMB6kDy4Kt+Di78PYhxurDwWSehdAEIL6JMByupm2eIRBvWPrp9oHQaMGz8G7l/lL0RHIk+8D5IePDfcoszz7Sr+WKQ+YmQFqB+YU="

after_success:
   - git checkout $TRAVIS_BRANCH
   - sudo chmod +x ci-scripts/release-script.sh
   - ./ci-scripts/release-script.sh
